---
title: "OpenHDF5"
author: "Jeffrey Stephens"
date: "June 20, 2016"
output: html_document
---
###About HDF5

```{r load libraries}
#load library
library(raster)
library(rhdf5)
library(rgdal)
```
##open data file 
```{r select file}
 f<-"../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"

h5ls(f)

```

##Import spatial Info
```{r import-spatial-info}
#import spatial info
mapInfo <- h5read(f,"map info", read.attributes = TRUE)

mapInfo

```

##Grab Reflectance Metadata
```{r get-refl-metadata}
#read in reflectance data attributes 

reflInfo <- h5readAttributes(f, "Reflectance")
reflInfo
# define scale factor
scaleFactor <- reflInfo$`Scale Factor`
#define no data vale
nodatavalue <- as.numeric(reflInfo$`data ignore value`)
str(nodatavalue)

```
##Import Data Dimensions
```{r import_dims}

#open file for viewing
fid <- H5Fopen(f)
# open the reflectance dataset

did <- H5Dopen(fid, "Reflectance")
did

#get data dimensions
sid <- H5Dget_space(did)
dims <- H5Sget_simple_extent_dims(sid)$size
dims

#close all open connections
H5Sclose(sid)
H5Dclose(did)
H5Fclose(fid)

```
#Read data reflectance
```{rread-data}
# extract slice of H5 file
b56 <- h5read(f, "Reflectance", index=list(1:dims[1], 1:dims[2],56))

b56
class(b56)

```

##Convert Data to Matrix

```{r conver-matrix}
b56 <- b56[,,1]

#lets plot some data
image(b56)

image(log(b56), main="log transformed data")
hist(b56)

```
##Clean up data
```{r data-clean-up}
#assign no data values to about
b56[b56==nodatavalue] <- NA
#apply scale factor
b56 <-b56/scaleFactor
hist(b56)

```
#transpose data
```{r transpose-data}
b56<- t(b56)
image(log(b56))
```

#Create spatial Extent
```{r create-spatial-extent}
#lets split out map info object
mapInfo <- strsplit(mapInfo, ",")
mapInfo <- unlist(mapInfo)
mapInfo

#value at 3 element in list
mapInfo[3]

#define upper left hand corner coordinate
xMin <- as.numeric(mapInfo[4])
yMax <- as.numeric(mapInfo[5])

#get spatial resolution 
xres <-as.numeric(mapInfo[6])
yres <- as.numeric(mapInfo[7])

#calculate Xmax and Ymin
xMax <- xMin + (dims[1] * xres)
yMin <- yMax -(dims[2]* yres)
```

#Create spatial extent
```{r create-extent}

#create extent object
rasExt <- extent(xMin, xMax, yMin, yMax)
rasExt

#create raster object
b56r <-raster(b56, crs=CRS("+init=epsg:32611"))
extent(b56r) <- rasExt
b56r

plot(b56r, main=Spatially reflectance data)

```
#import Neon Functions
```{r}
library(devtools)
library(ggplot2)
  


```






